name: frappe_sdk
description: The dart library for Frappe REST API, this package provides a clean and simple way to connect to your frappe instance.
version: 0.0.2

repository: https://github.com/elbeicktalat/frappe_sdk
issue_tracker: https://github.com/elbeicktalat/frappe_sdk/issues

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0
  flutter_cache_manager: ^3.4.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
